// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DataHandler>>
abstract class DataHandler implements RustOpaqueInterface {
  Int32List get dataList;

  bool get error;

  set dataList(Int32List dataList);

  set error(bool error);

  factory DataHandler(
          {required int numChannels,
          required String dir,
          required String filename}) =>
      RustLib.instance.api.crateApiDataHandlerDataHandlerNew(
          numChannels: numChannels, dir: dir, filename: filename);

  Future<void> process({required List<int> bytes});
}
